services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint: >
      sh -c "
        set -ex
        ollama serve & 
        sleep 3
        ollama pull nomic-embed-text
        ollama pull gemma3:12b
        ps -ef | grep 'ollama serve' | grep -v grep | awk '{print $2}' | xargs -r kill -9
        sleep 1
        ollama serve
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


